"""add timestamps to conversations

Revision ID: c23c33652536
Revises: 05f8bbe7ff3d
Create Date: 2026-05-20 14:17:58.227848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23c33652536'
down_revision: Union[str, Sequence[str], None] = '05f8bbe7ff3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'created_at')
    # ### end Alembic commands ###
